<!doctype html>
<html lang="es">
  <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="megakit,business,company,agency,multipurpose,modern,bootstrap4">
  
  <meta name="author" content="themefisher.com">

  <title>Servicio de Corte de Cesped - Corte de Pasto</title>

  <link href="https://cdn.lineicons.com/3.0/lineicons.css" rel="stylesheet">


  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{{asset('assets/plugins/bootstrap/css/bootstrap.min.css')}}">
  <!-- Icon Font Css -->
  <link rel="stylesheet" href="{{asset('assets/plugins/themify/css/themify-icons.css')}}">
  <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome/css/all.css')}}">
  <link rel="stylesheet" href="{{asset('assets/plugins/magnific-popup/dist/magnific-popup.css')}}">
  <!-- Owl Carousel CSS -->
  <link rel="stylesheet" href="{{asset('assets/plugins/slick-carousel/slick/slick.css')}}">
  <link rel="stylesheet" href="{{asset('assets/plugins/slick-carousel/slick/slick-theme.css')}}">

  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
  <style>
    .slider {
    background-size: cover;
    background-position: 10% 0%;
    padding: 0px 0 0px 0;
    height: 100vh;
    position: relative;
}
  
  @font-face {
  font-family: Garamond;
  src: url(assets/fonts/Garamond.ttf);
  }

  /* #### Generated By: http://www.cufonfonts.com #### */

    @font-face {
    font-family: 'Myriad Pro Regular';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Regular'), url('fonts/MYRIADPRO-REGULAR.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Condensed';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Condensed'), url('MYRIADPRO-COND.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Condensed Italic';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Condensed Italic'), url('MYRIADPRO-CONDIT.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Light';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Light'), url('MyriadPro-Light.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Semibold';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Semibold'), url('MYRIADPRO-SEMIBOLD.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Semibold Italic';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Semibold Italic'), url('MYRIADPRO-SEMIBOLDIT.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Bold Condensed';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Bold Condensed'), url('MYRIADPRO-BOLDCOND.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Bold';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Bold'), url('MYRIADPRO-BOLD.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Bold Italic';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Bold Italic'), url('MYRIADPRO-BOLDIT.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Myriad Pro Bold Condensed Italic';
    font-style: normal;
    font-weight: normal;
    src: local('Myriad Pro Bold Condensed Italic'), url('MYRIADPRO-BOLDCONDIT.woff') format('woff');
    }
  .block h1.animated.fadeInUp{
    font-family: Garamond;
    letter-spacing: 3px
  }
  .myriadPro{
    font-family: 'Myriad Pro Regular';
    letter-spacing: 1px;
    color:#444444;
  }
  .h6{
    font-family: Garamond;
    color:#3F0000;
  }

.rotating {
  display: inline-block;
  -webkit-transform-style: preserve-3d;
  -moz-transform-style: preserve-3d;
  -ms-transform-style: preserve-3d;
  -o-transform-style: preserve-3d;
  transform-style: preserve-3d;
  -webkit-transform: rotateX(0) rotateY(0) rotateZ(0);
  -moz-transform: rotateX(0) rotateY(0) rotateZ(0);
  -ms-transform: rotateX(0) rotateY(0) rotateZ(0);
  -o-transform: rotateX(0) rotateY(0) rotateZ(0);
  transform: rotateX(0) rotateY(0) rotateZ(0);
  -webkit-transition: 0.5s;
  -moz-transition: 0.5s;
  -ms-transition: 0.5s;
  -o-transition: 0.5s;
  transition: 0.5s;
  -webkit-transform-origin-x: 50%;
}

.rotating.flip {
  position: relative;
}

.rotating .front, .rotating .back {
  left: 0;
  top: 0;
  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  -ms-backface-visibility: hidden;
  -o-backface-visibility: hidden;
  backface-visibility: hidden;
}

.rotating .front {
  position: absolute;
  display: inline-block;
  -webkit-transform: translate3d(0,0,1px);
  -moz-transform: translate3d(0,0,1px);
  -ms-transform: translate3d(0,0,1px);
  -o-transform: translate3d(0,0,1px);
  transform: translate3d(0,0,1px);
}

.rotating.flip .front {
  z-index: 1;
}

.rotating .back {
  display: block;
  opacity: 0;
}

.rotating.spin {
  -webkit-transform: rotate(360deg) scale(0);
  -moz-transform: rotate(360deg) scale(0);
  -ms-transform: rotate(360deg) scale(0);
  -o-transform: rotate(360deg) scale(0);
  transform: rotate(360deg) scale(0);
}



.rotating.flip .back {
  z-index: 2;
  display: block;
  opacity: 1;
  
  -webkit-transform: rotateY(180deg) translate3d(0,0,0);
  -moz-transform: rotateY(180deg) translate3d(0,0,0);
  -ms-transform: rotateY(180deg) translate3d(0,0,0);
  -o-transform: rotateY(180deg) translate3d(0,0,0);
  transform: rotateY(180deg) translate3d(0,0,0);
}

.rotating.flip.up .back {
  -webkit-transform: rotateX(180deg) translate3d(0,0,0);
  -moz-transform: rotateX(180deg) translate3d(0,0,0);
  -ms-transform: rotateX(180deg) translate3d(0,0,0);
  -o-transform: rotateX(180deg) translate3d(0,0,0);
  transform: rotateX(180deg) translate3d(0,0,0);
}

.rotating.flip.cube .front {
  -webkit-transform: translate3d(0,0,100px) scale(0.9,0.9);
  -moz-transform: translate3d(0,0,100px) scale(0.85,0.85);
  -ms-transform: translate3d(0,0,100px) scale(0.85,0.85);
  -o-transform: translate3d(0,0,100px) scale(0.85,0.85);
  transform: translate3d(0,0,100px) scale(0.85,0.85);
}

.rotating.flip.cube .back {
  -webkit-transform: rotateY(180deg) translate3d(0,0,100px) scale(0.9,0.9);
  -moz-transform: rotateY(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  -ms-transform: rotateY(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  -o-transform: rotateY(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  transform: rotateY(180deg) translate3d(0,0,100px) scale(0.85,0.85);
}

.rotating.flip.cube.up .back {
  -webkit-transform: rotateX(180deg) translate3d(0,0,100px) scale(0.9,0.9);
  -moz-transform: rotateX(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  -ms-transform: rotateX(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  -o-transform: rotateX(180deg) translate3d(0,0,100px) scale(0.85,0.85);
  transform: rotateX(180deg) translate3d(0,0,100px) scale(0.85,0.85);
}

.slider {
    background: url(assets/images/corte_de_pasto.jpg) no-repeat;
    background-size: cover;
    background-position: 10% 0%;
    padding: 200px 0 280px0;
    position: relative;
}

.cta {
    background: url(assets/images/bg/home3.jpg) fixed 50% 50%; 
}


/*************/
.border-top {
    border-top: 0px solid #dee2e6!important;
}

  </style>

</head>

<body>


<!-- Header Start --> 

<div  class="main-wrapper">
<!-- Slider Start -->
<section class="slider">
  <div class="container">
    <div class="col-lg-9 col-md-10">
      <img src="{{asset('assets/images/logo_corte.png')}}" class="img-fluid mt-3">
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-10" style="position:absolute;
      bottom: 5%">
        <div class="block">
          <h1 id="demo" class="animated fadeInUp" style="font-family: Garamond"><span class="rotate">Corte de Césped, Mantenimiento de Jardínes, Precios a la Medida de su Necesidad</span></h1>
          <span class="d-block mb-3 text-white text-capitalize">Servicios de Corte y Mantenimiento de Césped. Atendemos Urgencias - Todos Los Días</span>
          <a href="https://wa.link/xbeucm" target="_blank" class="btn btn-main animated fadeInUp btn-round-full" >Consulte aquí<i class="btn-icon fa fa-angle-right ml-2"></i></a>
        </div>
      </div>
    </div>
  </div>
</section>





<section class="container section about position-relative">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="{{asset('assets/imgs/bodeadora3.jpg')}}" class="img-fluid">
      </div>
      <div class="col-md-6">

        <div class="about-item ">
          <span class="h6 text-color" style="text-transform: uppercase">AltoParque</span>
          <h2 class="mt-1 mb-4 position-relative content-title myriadPro"><span style="color:#70AD38">Buen Servicio</span> y Buen Precio </h2>
            <p class="mb-5">
                            Nos dedicamos al servicio de corte de pasto en CABA, Zona Norte y Zona Oeste<br>
                            Estamos atentos a cualquier consulta.<br>
                        </p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Section About End -->


 <!-- Section Cta Start --> 
<section class="section cta">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <div class="cta-item  bg-white p-5 rounded">
          <span class="h6 text-color">CONTÁCTENOS</span>
          <h2 class="mt-2 mb-4">Sus Consultas Son Siempre Bienvenidas!</h2>
                    <h3><a href="https://wa.link/xbeucm"><i class="ti-mobile mr-3 text-color"></i>11 3887-2953</a></h3>
        </div>
      </div>
    </div>
  </div>
</section>
<!--  Section Cta End-->



<!-- Section About Start -->
    <!--blog-->
      @yield('content')
    <!--endBlog-->

<!--  Section Services Start -->


<section class="section service border-top" style="background:url({{asset('assets/imgs/pasto.jpg')}}) repeat-x bottom; padding-bottom:400px ">
  <div class="container">


    <div class="row justify-content-center">
      <div class="col-lg-7 text-center">
        <div class="section-title">
          <img src="assets/images/logo_corte_plomo.png" class="img-fluid mb-3"><br>

          <span class="h6 text-color" style="text-transform: uppercase">Atención</span>
          <p class="mb-5">
          <br>Atendemos Hogares, Casas Quintas y Empresas 

          </p>
          <a href="https://wa.link/xbeucm" class="btn btn-main btn-round-full">Consultenos</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--  Section Services End -->


<!-- footer Start -->
<footer class="footer section">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-md-6 col-sm-6">
        <div class="widget">
          <h4 class="text-capitalize mb-4"><stron>NOSOTROS</stron></h4>
          <p>
            Nos Especializamos en Corte de Césped. Ofrecemos el servicio de lunes a domingos incluido feriados. Atendemos Urgencias.
          </p>
        </div>
      </div>
      <div class="col-lg-1 col-md-6 col-sm-6">
      </div>
      
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="widget">
          <h4 class="text-capitalize mb-4">CONTACTANOS</h4>
          <p>Será un placer atenderlo </p>

          <form action="#" class="sub-form">
            <a href="https://wa.link/xbeucm" class="btn btn-main btn-small">Click Aquí</a>
          </form>
        </div>
      </div>

      <div class="col-lg-3 ml-auto col-sm-6">
        <div class="widget">
          <div class="logo mb-4">
            <h3>Corte de <span style="color:#70AD38">Pasto</span> y Poda</h3>
          </div>
          <h6><a href="tel:+23-345-67890" >Soporte:</a></h6>
          <a href="https://wa.link/xbeucm"><span class="text-color h4">11 3887-2953</span></a>
        </div>
      </div>
    </div>
    
    <div class="footer-btm pt-4">
      <div class="row">
        <div class="col-lg-4 col-md-12 col-sm-12">
          <div class="copyright">
            &copy; Copyright Reserved to <span class="text-color">Corte de Pasto</span> by <a href="jofret.com" target="_blank">JOfret</a>
          </div>
        </div>

        <div class="col-lg-4 col-md-12 col-sm-12">
          <div class="copyright">
          Desarrollado por  <a href="jofret.com" target="_blank">JOfret</a>
          </div>
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12 text-left text-lg-left">
          <ul class="list-inline footer-socials">
            <!-- <li class="list-inline-item"><a href=""><i class="ti-facebook mr-2"></i>Facebook</a></li>
            <li class="list-inline-item"><a href=""><i class="ti-twitter mr-2"></i>Twitter</a></li>
            <li class="list-inline-item"><a href="/"><i class="ti-linkedin mr-2 "></i>Linkedin</a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
   
    </div>

    <!-- 
    Essential Scripts
    =====================================-->

    
    <!-- Main jQuery -->
    <script src="{{asset('assets/plugins/jquery/jquery.js')}}"></script>
    <script src="{{asset('assets/js/contact.js')}}"></script>
    <!-- Bootstrap 4.3.1 -->
    <script src="{{asset('assets/plugins/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
   <!--  Magnific Popup-->
    <script src="{{asset('assets/plugins/magnific-popup/dist/jquery.magnific-popup.min.js')}}"></script>
    <!-- Slick Slider -->
    <script src="{{asset('assets/plugins/slick-carousel/slick/slick.min.js')}}"></script>
    <!-- Counterup -->
    <script src="{{asset('assets/plugins/counterup/jquery.waypoints.min.js')}}"></script>
    <script src="{{asset('assets/plugins/counterup/jquery.counterup.min.js')}}"></script>

    <!-- Google Map -->
    <script src="{{asset('assets/plugins/google-map/map.js')}}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>  
    


    

    <script src="{{asset('assets/js/script.jjs')}}"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="{{asset('assets/js/jquery.simple-text-rotator.min.js')}}"></script>
    <script>
    $(document).ready(function(){
      $("#demo .rotate").textrotator({
        animation: "fade",
        speed: 2000
      });
    });
   
  </script>


  </body>
  </html>
   